name: ingatlan_figyelo_teszt
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1 # for state management
  http: ^0.13.4 # for handling HTTP requests
  json_annotation: ^4.6.0  # defines the annotations used by json_serializable 
  intl: ^0.17.0 #for localization and NumberFormat
  equatable: ^2.0.3

  
 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.3.1 # for json serialization
  build_runner: ^2.2.0 #for code generation (eg. json serialization)

flutter:

  uses-material-design: true
  assets:
   - assets/images/filters_widget/
  # - assets/a_dot_ham.jpeg

